import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "../utils/api";
import { useEffect, useState } from "react";
// zustand
import { useWorkoutModalStore } from "../store";
import WorkoutModal from "../components/workoutModal";
import HeaderCard from "../components/HeaderCard";

const Home: NextPage = () => {
  const { showWorkoutModal, setShowWorkoutModal, selectedWorkout, setSelectedWorkout } = useWorkoutModalStore();
  const userId = 1;

  const {
    data: userData,
    isLoading,
    error,
  } = api.example.getUser.useQuery({
    id: userId,
  });

  const {
    data: workoutData,
    isLoading: isLoading2,
    error: error2,
  } = api.example.getUncompletedWorkouts.useQuery({
    id: userId,
  });

  const {
    data: userStats,
    isLoading: userStatsLoading,
    error: userStatsError,
  } = api.example.getUserStats.useQuery({
    id: userId,
  });




  const today = new Date();

  useEffect(() => {
    console.log("selectedWorkout", selectedWorkout);
  }, [selectedWorkout]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#080f76] to-[#15162c]">
        {showWorkoutModal && <WorkoutModal />}
        <div className="grid w-full max-w-5xl grid-cols-8 gap-4">
          {userData?.username && <HeaderCard username={userData?.username} />}

          {/* workout cards */}
          <div className="col-span-8 flex h-24 flex-row items-center justify-center space-x-4 md:col-span-6">
            {workoutData?.slice(0, 5).map((workout, i) => (
              <div
                // if workout.workout_str?.split(" ")[0] === "Cold" we want bg color to be blue
                className={`flex h-24 w-full flex-col justify-between rounded ${
                  workout.title === "Cold plunge"
                    ? "bg-blue-200 p-3 hover:bg-blue-300"
                    : "bg-white p-3 hover:bg-gray-300"
                } ${i === 0 && "border-4 border-blue-500"}`}
                key={i}
                onClick={
                  i === 0
                    ? (e) => {
                      console.log("setting")
                      console.log("workout", workout)
                      console.log("selectedWorkout", selectedWorkout)
                        e.preventDefault();
                        setShowWorkoutModal(!showWorkoutModal);
                        setSelectedWorkout({
                          title: workout.title || "",
                          id: workout.id,
                        });
                      }
                    : (e) => e.preventDefault()
                    
                }
              >
                {/* first line of workout_str */}
                <div>{workout.title}</div>
                <div className="text-right opacity-60">
                  {
                    // i days after today
                    new Date(today.getTime() + (i + 1) * 24 * 60 * 60 * 1000)
                      .toDateString()
                      .split(" ")
                      .slice(1, 3)
                      .join(" ")
                  }
                </div>
              </div>
            ))}
          </div>

          {/* stats cards */}
          <div className="col-span-8 h-auto md:col-span-2">
            <div className="mb-4 flex h-24 w-full items-center bg-white p-2 hover:bg-gray-300">
              {/* img placeholder */}
              <div className="h-16 w-16 bg-gray-200"></div>
              <div className="ml-4 flex flex-col">
                <div className="text-xl font-bold">{userStats?.coldPlunges}</div>
                <div>cold plunges</div>
              </div>
            </div>
            <div className="mb-4 flex h-24 w-full items-center bg-white p-2 hover:bg-gray-300">
              {/* img placeholder */}
              <div className="h-16 w-16 bg-gray-200"></div>
              <div className="ml-4 flex flex-col">
                <div className="text-xl font-bold">{userStats?.workoutsCompleted}</div>
                <div>workouts complete</div>
              </div>
            </div>
            <div className="mb-4 flex h-24 w-full items-center bg-white p-2 hover:bg-gray-300">
              {/* img placeholder */}
              <div className="h-16 w-16 bg-gray-200"></div>
              <div className="ml-4 flex flex-col">
                <div className="text-xl font-bold">{userStats?.workoutsSkipped}</div>
                <div>skipped</div>
              </div>
            </div>
          </div>

          <div className="col-span-8 mb-4 flex h-auto flex-col space-y-2 bg-white md:col-span-6">
            <div className="mt-2 h-auto w-full justify-center px-4">
              <div className="flex flex-row items-center space-x-1 ">
                <div>Bryce</div>
                <div className="flex flex-row items-center justify-center space-x-1">
                  <div className="h-8 w-8 bg-green-500"></div>
                  <div className="h-8 w-8 bg-green-500"></div>
                  <div className="h-8 w-8 bg-green-500"></div>
                  <div className="h-8 w-8 bg-green-500"></div>
                  <div className="h-8 w-8 bg-green-500"></div>
                  <div className="h-8 w-8 bg-green-500"></div>
                  <div className="h-8 w-8 bg-green-500"></div>
                </div>
              </div>
            </div>
            <div className="h-auto w-full justify-center px-4">
              <div className="flex flex-row items-center space-x-1 ">
                <div>Braden</div>
                <div className="flex flex-row items-center justify-center space-x-1">
                  <div className="h-8 w-8 bg-green-500"></div>
                  <div className="h-8 w-8 bg-green-500"></div>
                  <div className="h-8 w-8 bg-green-500"></div>
                  <div className="h-8 w-8 bg-green-500"></div>
                  <div className="h-8 w-8 bg-green-500"></div>
                  <div className="h-8 w-8 bg-green-500"></div>
                  <div className="h-8 w-8 bg-green-500"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
